sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t ca024/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test -- --coverage

after_success:
  - docker build -t ca024/multi-client ./client
  - docker build -t ca024/multi-nginx ./nginx
  - docker build -t ca024/multi-server ./server
  - docker build -t ca024/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push ca024/multi-client
  - docker push ca024/multi-nginx
  - docker push ca024/multi-server
  - docker push ca024/multi-worker


